<a href="https://colab.research.google.com/github/manojabacholla/NASSCOM-LAB/blob/main/numpy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [4]:

import numpy as np

arr1 = np.arange(0, 10, 2)
print("Array using arange:", arr1)
print("Array using arange:", arr1)
arr2 = np.linspace(0, 1, 5)
print("Array using linspace:", arr2)
arr3 = np.arange(1, 10).reshape((3, 3))
print("Reshaped Array (3x3):\n", arr3)
print("Flattened version:", arr3.flatten())
data = np.array([[5, 8, 9], [2, 4, 6]])
print("Original Data:\n", data)
print("Sum of all elements:", np.sum(data))
print("Column-wise sum:", np.sum(data, axis=0))
print("Row-wise mean:", np.mean(data, axis=1))
print("Max value:", np.max(data))
print("Index of max value (flattened):", np.argmax(data))
print("Min value:", np.min(data))
print("Standard Deviation:", np.std(data))
a = np.array([3, 1, 7, 2, 9])
print("Original Array:", a)
sorted_array = np.sort(a)
print("Sorted Array:", sorted_array)
idx = np.where(a > 4)
print("Indices where value > 4:", idx)
print("Values > 4:", a[idx])
A = np.array([[1, 2], [3, 4]])
B = np.array([10, 20])
print("Matrix A:\n", A)
print("Vector B:", B)
C = A + B
print("Broadcasted Addition Result:\n", C)
nums = np.array([1, 2, 3, 4, 5])
mask = nums > 3
print("Mask (nums > 3):", mask)
filtered = nums[mask]
print("Filtered values:", filtered)
result = np.where(nums % 2 == 0, "Even", "Odd")
print("Even or Odd:", result)
arr_orig = np.array([10, 20, 30])
arr_view = arr_orig[:]
arr_view[0] = 99
print("Original After View Change:", arr_orig)
arr_copy = arr_orig.copy()
arr_copy[0] = 55
print("Original After Copy Change:", arr_orig)
print("Copy:", arr_copy)
x = np.array([1, 2, 3])
y = np.array([4, 5, 6])
v_stack = np.vstack((x, y))
print("Vertical Stack:\n", v_stack)
h_stack = np.hstack((x, y))
print("Horizontal Stack:\n", h_stack)
z = np.arange(10)
split_arr = np.array_split(z, 3)
print("Split into 3 parts:", split_arr)
rand_ints = np.random.randint(0, 100, size=(3, 3))
print("Random Integers:\n", rand_ints)
rand_norm = np.random.randn(2, 4)
print("Random Normal Distribution:\n", rand_norm)
choices = np.random.choice([1, 3, 5, 7], size=5)
print("Random Choices:", choices)
np.random.seed(42)
print("Seeded Random Number:", np.random.rand())
arr = np.array([10, 20, 30, 40, 50, 60])
print("Original 1D Array:", arr)

print("Element at index 0:", arr[0])
print("Element at last index:", arr[-1])
print("Slice from index 1 to 4:", arr[1:4])
print("Every second element:", arr[::2])
print("Reversed array:", arr[::-1])
matrix = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

print("Original Matrix:\n", matrix)
print("Element at (1,2):", matrix[1, 2])
print("First row:", matrix[0, :])
print("Second column:", matrix[:, 1])
print("Top-left 2x2 block:\n", matrix[:2, :2])
arr = np.array([5, 10, 15, 20, 25, 30])
mask = arr > 15
print("Boolean Mask:", mask)
print("Values greater than 15:", arr[mask])
print("Even numbers > 10:", arr[(arr > 10) & (arr % 2 == 0)])

Array using arange: [0 2 4 6 8]
Array using arange: [0 2 4 6 8]
Array using linspace: [0.   0.25 0.5  0.75 1.  ]
Reshaped Array (3x3):
 [[1 2 3]
 [4 5 6]
 [7 8 9]]
Flattened version: [1 2 3 4 5 6 7 8 9]
Original Data:
 [[5 8 9]
 [2 4 6]]
Sum of all elements: 34
Column-wise sum: [ 7 12 15]
Row-wise mean: [7.33333333 4.        ]
Max value: 9
Index of max value (flattened): 2
Min value: 2
Standard Deviation: 2.3570226039551585
Original Array: [3 1 7 2 9]
Sorted Array: [1 2 3 7 9]
Indices where value > 4: (array([2, 4]),)
Values > 4: [7 9]
Matrix A:
 [[1 2]
 [3 4]]
Vector B: [10 20]
Broadcasted Addition Result:
 [[11 22]
 [13 24]]
Mask (nums > 3): [False False False  True  True]
Filtered values: [4 5]
Even or Odd: ['Odd' 'Even' 'Odd' 'Even' 'Odd']
Original After View Change: [99 20 30]
Original After Copy Change: [99 20 30]
Copy: [55 20 30]
Vertical Stack:
 [[1 2 3]
 [4 5 6]]
Horizontal Stack:
 [1 2 3 4 5 6]
Split into 3 parts: [array([0, 1, 2, 3]), array([4, 5, 6]), array([7, 8, 9])]
Rand